### ISSUE TITLE
Naming Scheme

### ISSUE THREAD

**Issue by Pharylon** [AiBattleground/BotWars#1]
In the GameState JSON, the players are identified as "p1" and "p2," but your'e told which player you are by color ("r" and "b"). You just have to know from outside information that p1 is always "r" and p2 is always "b". This is dumb, and we should change it in our implementation. We should either change the name of the p1 and p2 objects to be "r" and "b" or else add an identifier to the player class. So 

```
"p1": {
    "energy": 0,
    "spawn": 5
  },
```

Becomes 

```
"p1": {
    "energy": 0,
    "spawn": 5,
    "color": r
  },
```

**Comment by Dubman25** [comment]
I'm currently re-familiarizing myself with the API, but if I recall correctly the issue was identifying which players values were yours and which were the other players.  The reason, I think, was that you wouldn't know if you were red or blue before the game began.  Your color was assigned by the server.  Perhaps we should look at the handshaking that happens at game initiation?  Perhaps something like this for the object would work:

"player": {
                 "human": "you",
                 "energy": 0,
                 "spawn": 5,
                 "color": r
              }

"player": {
                "human": "opponent",
                "energy": 2,
                "spawn": 92,
                "color": b
              }

I do think the color, as assigned by the server should be included somewhere.  This way a rendering solution implemented by the player and one shown on the server would use the same colors for the the same players.  This would limit confusion.

My two cents,

Dub

**Comment by Pharylon** [comment]
Although this might be getting into "quibble" territory, the more I've thought about it the more I think we should get rid of colors from the API altogether. Maybe I've been doing too much MVC lately, but I don't think the logic should have any awareness of the display. If the local version wants to render them in orange and green, fine. If it wants to render the enemy as always red and itself as always blue, fine. 

So instead of "p1" and "p2" let's just call them "player" and "enemy." So no more having to work out which one you are. The JSON would then use marks like "p" and "e" instead of "r" and "b" for bot locations.

**Comment by Dubman25** [comment]
I'm ok with or without it.

Keith

**Comment by Pharylon** [comment]
Here's an idea to toss out there: let the bot specify what color it should be rendered in. So each bot could have a "look" if it wanted to.

**Comment by Dubman25** [comment]
Now you're talking.  And a backup color in case I collisions.

Keith
